api_keys:
  serpapi: "76f3ea1f6758054f7bb79457102d937bc1dff7ae4a1ecc98e6a5751530a11824"
  serpwow: "063CF8C35D1E42FF96E7262A2AD04C00"
  searchapi: "Ci1r51NbstLbdH8F2KVEh6jT"

tor:
  control_password: "controlpass" 
  control_port: 9151
  proxy_port: 9150

api_parameters:
  all:
    max_terms: 5

api_modes:
  - name: "trendspy"
    description: "trendspy only"
    api_order:
      - trendspy

  - name: "serpapi"
    description: "serpapi"
    api_order:
      - serpapi

  - name: "serpwow"
    description: "serpwow"
    api_order:
      - serpwow

  - name: "searchapi"
    description: "searchapi"
    api_order:
      - searchapi

  - name: "applescript_safari"
    description: "applescript_safari"
    api_order:
      - applescript_safari

  - name: "dummy"
    description: "dummy data, no api call"
    api_order:
      - dummy_api

  - name: "smart_tpy"
    description: "trendspy:serpapi:serpwow:searchapi"
    api_order:
      - trendspy
      - serpapi
      - serpwow
      - searchapi

  - name: "smart_pyt"
    description: "NOT IMPLEMENTED! pytrends:serpapi:serpwow:searchapi"
    api_order:
      - pytrends
      - serpapi
      - serpwow
      - searchapi

  - name: "smart_sel"
    description: "selenium:serpapi:serpwow:searchapi"
    api_order:
      - selenium
      - serpapi
      - serpwow
      - searchapi
  
  - name: "smart_pay"
    description: "serpapi:serpwow:searchapi"
    api_order:
      - serpapi
      - serpwow
      - searchapi
